// Configuration
const IMAGE_FOLDER = 'protein_images';
// const IMAGE_FOLDER = 'https://proteinaging.oss-rg-china-mainland.aliyuncs.com/protein_images'; // 或自定义域名
const DEFAULT_IMAGE = 'NEFL_seq.10082.251';
const DEBOUNCE_DELAY = 300; // milliseconds

// State
let allProteins = [];
let filteredProteins = [];
let selectedIndex = -1;
let searchTimeout = null;

// DOM elements
const searchInput = document.getElementById('searchInput');
const searchResults = document.getElementById('searchResults');
const proteinImage = document.getElementById('proteinImage');
const loadingIndicator = document.getElementById('loadingIndicator');
const errorMessage = document.getElementById('errorMessage');
const imageInfo = document.getElementById('imageInfo');

// Initialize
document.addEventListener('DOMContentLoaded', () => {
    // Log configuration for debugging
    console.log('Image folder:', IMAGE_FOLDER);
    console.log('Default image:', DEFAULT_IMAGE);
    console.log('User agent:', navigator.userAgent);
    
    setupEventListeners();
    initializeProteins().then(() => {
        // Set default value in search box
        searchInput.value = DEFAULT_IMAGE;
        // Show all proteins in dropdown initially
        filteredProteins = [...allProteins];
        displayResults();
        loadDefaultImage();
    }).catch(error => {
        console.error('Initialization error:', error);
    });
});

// Fetch all protein filenames
async function initializeProteins() {
    try {
        // Try to fetch a list file first
        try {
            const response = await fetch(`list.json`);
            if (response.ok) {
                allProteins = await response.json();
                console.log(`Loaded ${allProteins.length} proteins from list.json`);
            } else {
                // Fallback: generate list from common patterns
                console.warn('list.json not found, using fallback list. Please run generate-list.js or generate-list.py');
                allProteins = generateProteinList();
            }
        } catch (e) {
            // If list.json doesn't exist, generate list
            console.warn('Could not load list.json, using fallback list. Please run generate-list.js or generate-list.py');
            allProteins = generateProteinList();
        }
        
        filteredProteins = [...allProteins];
    } catch (error) {
        console.error('Error initializing proteins:', error);
        allProteins = generateProteinList();
        filteredProteins = [...allProteins];
    }
}

// Generate a placeholder list (you should replace this with actual data)
// Note: This is only a fallback. You should provide a list.json file with all protein names
function generateProteinList() {
    // Return only the default protein as fallback
    // The actual list should come from list.json generated by generate-list.js or generate-list.py
    return [DEFAULT_IMAGE];
}

// Setup event listeners
function setupEventListeners() {
    searchInput.addEventListener('input', handleSearchInput);
    searchInput.addEventListener('keydown', handleKeyDown);
    searchInput.addEventListener('focus', () => {
        // Show results when input is focused
        if (filteredProteins.length > 0) {
            displayResults();
            showResults();
        }
    });
    searchInput.addEventListener('blur', () => {
        // Delay hiding to allow click events
        setTimeout(() => {
            searchResults.classList.remove('active');
        }, 200);
    });
    
    // Prevent image drag
    proteinImage.addEventListener('dragstart', (e) => e.preventDefault());
}

// Handle search input with debouncing
function handleSearchInput(e) {
    const query = e.target.value.trim();
    
    clearTimeout(searchTimeout);
    
    searchTimeout = setTimeout(() => {
        if (query === '') {
            // Show all proteins when search is empty
            filteredProteins = [...allProteins];
            selectedIndex = -1;
            displayResults();
            showResults();
            return;
        }
        
        performSearch(query);
    }, DEBOUNCE_DELAY);
}

// Perform fuzzy search
function performSearch(query) {
    const lowerQuery = query.toLowerCase();
    
    filteredProteins = allProteins.filter(protein => {
        const lowerProtein = protein.toLowerCase();
        return lowerProtein.includes(lowerQuery) || 
               fuzzyMatch(lowerProtein, lowerQuery);
    });
    
    selectedIndex = -1;
    displayResults();
    showResults();
}

// Simple fuzzy match function
function fuzzyMatch(text, pattern) {
    let patternIdx = 0;
    for (let i = 0; i < text.length && patternIdx < pattern.length; i++) {
        if (text[i] === pattern[patternIdx]) {
            patternIdx++;
        }
    }
    return patternIdx === pattern.length;
}

// Display search results
// For performance with 10,000+ items, we render all items but use efficient DOM manipulation
function displayResults() {
    if (filteredProteins.length === 0) {
        searchResults.innerHTML = '<div class="search-result-item">No results found</div>';
        return;
    }
    
    const query = searchInput.value.trim().toLowerCase();
    const totalCount = filteredProteins.length;
    
    // Use document fragment for better performance
    const fragment = document.createDocumentFragment();
    
    // Render all items (browsers can handle 10,000+ DOM elements, especially simple ones)
    filteredProteins.forEach((protein, index) => {
        const highlighted = highlightMatch(protein, query);
        const item = document.createElement('div');
        item.className = `search-result-item ${index === selectedIndex ? 'selected' : ''}`;
        item.setAttribute('data-index', index);
        item.setAttribute('data-protein', protein);
        item.innerHTML = `<span class="gene-name">${highlighted}</span>`;
        
        // Add click listener
        item.addEventListener('click', () => {
            selectProtein(protein);
        });
        
        fragment.appendChild(item);
    });
    
    // Clear and append in one operation
    searchResults.innerHTML = '';
    searchResults.appendChild(fragment);
    
    // Scroll to selected item
    if (selectedIndex >= 0 && selectedIndex < filteredProteins.length) {
        const selectedItem = searchResults.querySelector(`[data-index="${selectedIndex}"]`);
        if (selectedItem) {
            // Use setTimeout to ensure DOM is updated
            setTimeout(() => {
                selectedItem.scrollIntoView({ block: 'nearest', behavior: 'smooth' });
            }, 0);
        }
    }
}

// Highlight matching text
function highlightMatch(text, query) {
    if (!query) return text;
    
    const lowerText = text.toLowerCase();
    const lowerQuery = query.toLowerCase();
    const index = lowerText.indexOf(lowerQuery);
    
    if (index === -1) {
        // Fuzzy highlight - highlight matching characters
        let result = '';
        let queryIdx = 0;
        for (let i = 0; i < text.length; i++) {
            if (queryIdx < query.length && 
                lowerText[i] === lowerQuery[queryIdx]) {
                result += `<span class="highlight">${text[i]}</span>`;
                queryIdx++;
            } else {
                result += text[i];
            }
        }
        return result;
    }
    
    return text.substring(0, index) +
           `<span class="highlight">${text.substring(index, index + query.length)}</span>` +
           text.substring(index + query.length);
}

// Handle keyboard navigation
function handleKeyDown(e) {
    // If results are not shown, show them on arrow down
    if (!searchResults.classList.contains('active')) {
        if ((e.key === 'ArrowDown' || e.key === 'ArrowUp') && filteredProteins.length > 0) {
            e.preventDefault();
            displayResults();
            showResults();
            if (e.key === 'ArrowDown') {
                selectedIndex = 0;
            } else {
                selectedIndex = filteredProteins.length - 1;
            }
            displayResults();
            return;
        }
        if (e.key === 'Enter' && searchInput.value.trim()) {
            performSearch(searchInput.value.trim());
            showResults();
        }
        return;
    }
    
    if (filteredProteins.length === 0) {
        return;
    }
    
    switch (e.key) {
        case 'ArrowDown':
            e.preventDefault();
            selectedIndex = Math.min(selectedIndex + 1, filteredProteins.length - 1);
            displayResults();
            break;
            
        case 'ArrowUp':
            e.preventDefault();
            selectedIndex = Math.max(selectedIndex - 1, -1);
            displayResults();
            break;
            
        case 'Enter':
            e.preventDefault();
            if (selectedIndex >= 0 && selectedIndex < filteredProteins.length) {
                selectProtein(filteredProteins[selectedIndex]);
            } else if (filteredProteins.length > 0) {
                selectProtein(filteredProteins[0]);
            }
            break;
            
        case 'Escape':
            searchResults.classList.remove('active');
            selectedIndex = -1;
            break;
    }
}

// Show search results
function showResults() {
    if (filteredProteins.length > 0) {
        searchResults.classList.add('active');
    } else {
        searchResults.classList.remove('active');
    }
}

// Select and load protein image
function selectProtein(proteinName) {
    searchInput.value = proteinName;
    searchResults.classList.remove('active');
    selectedIndex = -1;
    loadImage(proteinName);
}

// Load default image
function loadDefaultImage() {
    loadImage(DEFAULT_IMAGE);
}

// Load protein image
function loadImage(proteinName) {
    // Construct image path - ensure proper URL format
    let imagePath = `${IMAGE_FOLDER}/${proteinName}.png`;
    
    // Remove double slashes if IMAGE_FOLDER ends with / and path starts with /
    imagePath = imagePath.replace(/([^:]\/)\/+/g, '$1');
    
    // Show loading
    loadingIndicator.classList.add('active');
    errorMessage.style.display = 'none';
    proteinImage.classList.remove('loaded');
    proteinImage.style.display = 'none';
    imageInfo.textContent = '';
    
    // Clear previous image and event handlers
    proteinImage.src = '';
    proteinImage.onload = null;
    proteinImage.onerror = null;
    
    // Set up timeout for slow connections (mobile networks)
    const timeout = setTimeout(() => {
        console.warn('Image load timeout:', imagePath);
        showError('Image loading timeout. Please check your connection.');
    }, 30000); // 30 seconds timeout
    
    // Handle successful load
    const handleImageLoad = () => {
        clearTimeout(timeout);
        loadingIndicator.classList.remove('active');
        proteinImage.classList.add('loaded');
        proteinImage.style.display = 'block';
        imageInfo.textContent = proteinName;
        console.log('Image loaded successfully:', proteinName);
    };
    
    // Handle load error with detailed error info
    const handleImageError = (error) => {
        clearTimeout(timeout);
        console.error('Image load error:', imagePath, error);
        showError(`Failed to load image: ${proteinName}. Please check the image path and network connection.`);
    };
    
    // Set up event handlers before setting src
    proteinImage.onload = handleImageLoad;
    proteinImage.onerror = handleImageError;
    
    // Set image attributes
    proteinImage.alt = `Protein visualization: ${proteinName}`;
    
    // For mobile browsers, add loading="lazy" attribute
    if (!proteinImage.hasAttribute('loading')) {
        proteinImage.setAttribute('loading', 'eager');
    }
    
    // Start loading - set src last to trigger load
    proteinImage.src = imagePath;
    
    // Fallback: if image is already cached and loaded immediately
    if (proteinImage.complete && proteinImage.naturalWidth > 0) {
        handleImageLoad();
    }
}

// Show error message
function showError(customMessage) {
    loadingIndicator.classList.remove('active');
    errorMessage.style.display = 'block';
    proteinImage.classList.remove('loaded');
    imageInfo.textContent = '';
    
    // Update error message if custom message provided
    if (customMessage) {
        const errorText = errorMessage.querySelector('p');
        if (errorText) {
            errorText.textContent = customMessage;
        }
    }
}

